[global]
run-mode = DEBUG
listening-port = 6809
listening-host = asterix.local
listening-https-keyfile = /home/nplagell/certs/asterix.local_private.key
listening-https-certfile = /home/nplagell/certs/asterix.local_certificate.crt

[mpd.connexion]
mpd-address = localhost
mpd-port = 6600

[web.client]
use-web-client = True

