[global]
run-mode = DEBUG
webradios_pl_json_file = configuration/webradios_pl_config.json

[mpd.connexion]
#address = /home/nplagell/.config/mpd/socket
address = localhost
port = 6600

[web.client]
use-web-client = True



